"""
Seed questions for all roles × experience levels.
Each role gets ~10 questions shared across all experience levels.
"""

EXPERIENCE_LEVELS = ["0-1 years", "1-3 years", "3-5 years", "5+ years"]

QUESTIONS_BY_ROLE = {
    "Full-Stack Developer": [
        "Explain the difference between REST and GraphQL APIs.",
        "How do you handle authentication in a full-stack application?",
        "What is the difference between server-side rendering and client-side rendering?",
        "Describe how you would design a scalable web application architecture.",
        "What are Web Sockets and when would you use them over HTTP?",
        "Explain the concept of database indexing and when you would use it.",
        "How do you manage state in a large React or Vue application?",
        "What is CI/CD and how have you implemented it in a project?",
        "How do you handle CORS in a full-stack project?",
        "What strategies do you use for optimizing frontend performance?",
        "Describe a challenging bug you fixed and your debugging approach.",
        "What is the difference between SQL and NoSQL databases?",
    ],
    "Software Engineer": [
        "Explain the SOLID principles of object-oriented design.",
        "What is the difference between a process and a thread?",
        "Describe a time you optimized a slow piece of code.",
        "What is Big O notation? Give examples of O(n) and O(log n) algorithms.",
        "How do you approach code reviews?",
        "What design patterns have you used in production?",
        "Explain the concept of dependency injection.",
        "What is the difference between unit testing and integration testing?",
        "How do you handle version control in a team environment?",
        "What are microservices and when should you use them?",
        "How do you ensure code quality in your projects?",
        "Describe your experience with Agile or Scrum methodologies.",
    ],
    "Mobile App Developer": [
        "What is the difference between native and cross-platform mobile development?",
        "How do you handle offline functionality in a mobile app?",
        "Explain the mobile app lifecycle for iOS or Android.",
        "How do you optimize battery usage in a mobile application?",
        "What strategies do you use for mobile app performance optimization?",
        "How do you handle push notifications in mobile apps?",
        "What is the difference between React Native and Flutter?",
        "How do you manage state in a React Native application?",
        "What security best practices do you follow for mobile apps?",
        "How do you handle deep linking in mobile applications?",
        "Describe your App Store or Play Store submission experience.",
        "How do you test mobile applications across different devices?",
    ],
    "QA/Automation Engineer": [
        "What is the difference between manual testing and automated testing?",
        "Explain the testing pyramid and why it matters.",
        "What frameworks have you used for test automation?",
        "How do you write a good test case?",
        "What is regression testing and when do you perform it?",
        "Explain the concept of test-driven development (TDD).",
        "How do you handle flaky tests in a CI pipeline?",
        "What is the difference between black-box and white-box testing?",
        "How do you prioritize which tests to automate?",
        "Describe your experience with Selenium, Cypress, or Playwright.",
        "What is performance testing and what tools have you used?",
        "How do you integrate automated tests into a CI/CD pipeline?",
    ],
    "Blockchain Developer": [
        "Explain the difference between a public and private blockchain.",
        "What is a smart contract and how does it work?",
        "How does the Ethereum Virtual Machine (EVM) work?",
        "What is gas in Ethereum and how is it calculated?",
        "Explain the concept of consensus mechanisms (PoW vs PoS).",
        "What is a decentralized application (dApp)?",
        "How do you secure a smart contract against common vulnerabilities?",
        "What is the difference between fungible and non-fungible tokens?",
        "How do you test smart contracts?",
        "What are Layer 2 scaling solutions?",
        "Explain how IPFS works and when you would use it.",
        "What is the difference between Solidity and Rust for blockchain development?",
    ],
    "Python Developer": [
        "What is the difference between a list and a tuple in Python?",
        "Explain Python's GIL (Global Interpreter Lock) and its impact.",
        "What are decorators in Python and how do you use them?",
        "Explain generators and when you would use them over lists.",
        "What is the difference between deepcopy and shallow copy?",
        "How does Python's garbage collection work?",
        "What are context managers and how do you implement one?",
        "Explain the difference between multiprocessing and multithreading in Python.",
        "What are Python type hints and why are they useful?",
        "How do you handle exceptions in Python best practices?",
        "What is the difference between asyncio and threading?",
        "Describe your experience with Python web frameworks (Django/FastAPI/Flask).",
    ],
    "Java Developer": [
        "Explain the difference between JDK, JRE, and JVM.",
        "What is garbage collection in Java and how does it work?",
        "Explain the concept of Java generics.",
        "What is the difference between an interface and an abstract class?",
        "How does Java handle concurrency and thread safety?",
        "What are Java Streams and how do you use them?",
        "Explain the Spring Framework's dependency injection.",
        "What is the difference between HashMap and ConcurrentHashMap?",
        "How does the JVM optimize code at runtime (JIT compilation)?",
        "What are Java design patterns you have used in production?",
        "Explain the difference between checked and unchecked exceptions.",
        "How do you profile and optimize a slow Java application?",
    ],
    "AI/ML Engineer": [
        "Explain the bias-variance tradeoff in machine learning.",
        "What is the difference between supervised and unsupervised learning?",
        "How do you handle imbalanced datasets?",
        "What is cross-validation and why is it important?",
        "Explain how gradient descent works.",
        "What is the difference between bagging and boosting?",
        "How do you prevent overfitting in a neural network?",
        "What is the attention mechanism in transformers?",
        "Explain the difference between precision and recall.",
        "How do you deploy an ML model to production?",
        "What is feature engineering and why is it important?",
        "Describe a machine learning project you built from scratch.",
    ],
    "Data Scientist": [
        "What is the difference between correlation and causation?",
        "Explain how Principal Component Analysis (PCA) works.",
        "How do you handle missing data in a dataset?",
        "What is A/B testing and how do you design one?",
        "Explain the difference between parametric and non-parametric tests.",
        "How do you communicate model results to non-technical stakeholders?",
        "What is the difference between a Type I and Type II error?",
        "How do you validate a statistical model?",
        "Describe your experience with SQL for data analysis.",
        "What Python libraries do you use most for data science?",
        "How do you handle outliers in data?",
        "Describe a data science project where your insights drove a business decision.",
    ],
    "Data Analyst": [
        "Explain the difference between INNER JOIN and LEFT JOIN in SQL.",
        "How do you clean and prepare a messy dataset?",
        "What visualization tools have you used (Tableau, Power BI, etc.)?",
        "How do you identify trends in time-series data?",
        "What is the difference between a dimension and a metric in analytics?",
        "Explain what a pivot table is and when you use it.",
        "How do you present data insights to management?",
        "What is cohort analysis and when is it useful?",
        "How do you ensure data accuracy in your reports?",
        "What SQL window functions have you used?",
        "Describe a dashboard you built and the business impact it had.",
        "How do you define KPIs for a business problem?",
    ],
    "Prompt Engineer": [
        "What is prompt engineering and why does it matter?",
        "Explain the difference between zero-shot, one-shot, and few-shot prompting.",
        "How do you reduce hallucinations in LLM outputs?",
        "What is chain-of-thought prompting?",
        "How do you evaluate the quality of an LLM's response?",
        "What is the difference between a system prompt and a user prompt?",
        "How do you design prompts for structured JSON output?",
        "What is RAG (Retrieval-Augmented Generation) and how does it improve prompts?",
        "How do you handle adversarial inputs or prompt injection attacks?",
        "What tools do you use to test and iterate on prompts?",
        "Explain temperature and top-p parameters in LLMs.",
        "Describe a complex prompt you designed and the problem it solved.",
    ],
    "NLP Specialist": [
        "What is the difference between stemming and lemmatization?",
        "Explain how TF-IDF works.",
        "What is word embedding and how does Word2Vec work?",
        "Explain the transformer architecture at a high level.",
        "What is named entity recognition (NER) and how is it used?",
        "How do you fine-tune a pre-trained language model?",
        "What is sentiment analysis and what models work best for it?",
        "How do you evaluate an NLP model's performance?",
        "What is the difference between BERT and GPT architectures?",
        "How do you handle multilingual text in NLP pipelines?",
        "What is tokenization and why does it matter?",
        "Describe an NLP project you built and its business impact.",
    ],
    "Cloud Architect": [
        "What is the difference between IaaS, PaaS, and SaaS?",
        "How do you design a highly available architecture on AWS/Azure/GCP?",
        "What is the shared responsibility model in cloud security?",
        "Explain the difference between vertical and horizontal scaling.",
        "How do you optimize cloud costs in a large organization?",
        "What is a VPC and how do you design one securely?",
        "Explain the CAP theorem and its relevance to distributed systems.",
        "How do you design for disaster recovery in the cloud?",
        "What is infrastructure as code (IaC) and what tools have you used?",
        "How do you design a multi-region cloud deployment?",
        "What is a service mesh and when would you use one?",
        "Describe the largest cloud architecture you have designed.",
    ],
    "DevOps Engineer": [
        "What is the difference between continuous integration and continuous deployment?",
        "Explain how Docker containers differ from virtual machines.",
        "What is Kubernetes and what problems does it solve?",
        "How do you implement a blue-green deployment?",
        "What monitoring and observability tools have you used?",
        "Explain the concept of infrastructure as code.",
        "How do you handle secrets management in a CI/CD pipeline?",
        "What is a Helm chart and how do you use it?",
        "How do you design a rollback strategy for deployments?",
        "What is the difference between Docker Compose and Kubernetes?",
        "How do you implement auto-scaling in a cloud environment?",
        "Describe a production incident you resolved and what you learned.",
    ],
    "Site Reliability Engineer (SRE)": [
        "What is an SLI, SLO, and SLA? Give examples.",
        "How do you approach on-call rotations and incident response?",
        "What is error budgeting and how do you use it?",
        "Explain the concept of chaos engineering.",
        "How do you implement distributed tracing?",
        "What is the difference between availability and reliability?",
        "How do you reduce MTTR (Mean Time to Recovery)?",
        "What tools do you use for log aggregation and analysis?",
        "How do you design a post-mortem for a production incident?",
        "What is capacity planning and how do you approach it?",
        "Explain the four golden signals of monitoring.",
        "Describe the most complex production issue you have resolved.",
    ],
    "Network Engineer": [
        "Explain the OSI model and the function of each layer.",
        "What is the difference between TCP and UDP?",
        "How does BGP routing work?",
        "What is subnetting and how do you calculate subnets?",
        "Explain the difference between a hub, switch, and router.",
        "What is VLAN and why is it used?",
        "How does DNS resolution work step by step?",
        "What is a firewall and how does it differ from an IDS/IPS?",
        "Explain the concept of NAT (Network Address Translation).",
        "What is QoS and when is it important?",
        "How do you troubleshoot a network connectivity issue?",
        "Describe your experience with network monitoring tools.",
    ],
    "Systems Administrator": [
        "What is the difference between a process and a daemon?",
        "How do you monitor system performance on Linux?",
        "What is LVM and how do you manage it?",
        "How do you automate repetitive admin tasks?",
        "Explain how SSH key-based authentication works.",
        "What is RAID and when would you use RAID 5 vs RAID 10?",
        "How do you harden a Linux server for production?",
        "What is cron and how do you schedule jobs with it?",
        "How do you troubleshoot a server that is running out of disk space?",
        "What backup strategies do you use and how do you test restores?",
        "Explain how you would set up a high-availability web server.",
        "Describe your experience with configuration management tools (Ansible, Puppet).",
    ],
    "Cybersecurity Analyst": [
        "What is the CIA triad in cybersecurity?",
        "How do you investigate a phishing attack?",
        "What is the difference between IDS and IPS?",
        "Explain the MITRE ATT&CK framework.",
        "How do you perform a vulnerability assessment?",
        "What is a SIEM and how do you use it?",
        "Explain the concept of defense in depth.",
        "What is lateral movement in a cyberattack?",
        "How do you respond to a data breach?",
        "What is the difference between symmetric and asymmetric encryption?",
        "How do you prioritize vulnerabilities for remediation?",
        "Describe a security incident you investigated and resolved.",
    ],
    "Ethical Hacker / Penetration Tester": [
        "What are the phases of a penetration test?",
        "Explain the difference between a vulnerability scan and a pentest.",
        "What is SQL injection and how do you test for it?",
        "How do you perform a man-in-the-middle attack in a controlled environment?",
        "What is a privilege escalation attack?",
        "What tools do you use for network reconnaissance?",
        "Explain what a buffer overflow vulnerability is.",
        "How do you write a penetration test report?",
        "What is the OWASP Top 10?",
        "How do you approach social engineering tests?",
        "What is Metasploit and how have you used it?",
        "Describe the most interesting vulnerability you have discovered.",
    ],
    "Security Architect": [
        "How do you design a zero-trust architecture?",
        "What is threat modeling and how do you conduct it?",
        "Explain the principle of least privilege.",
        "How do you design a PKI (Public Key Infrastructure)?",
        "What is the difference between authentication and authorization?",
        "How do you integrate security into the SDLC (DevSecOps)?",
        "What is federated identity and how does SAML/OAuth work?",
        "How do you evaluate third-party vendor security risk?",
        "What is a security baseline and how do you enforce it?",
        "How do you design for compliance with GDPR or ISO 27001?",
        "Explain network segmentation and micro-segmentation.",
        "Describe the security architecture of a system you designed.",
    ],
    "Incident Responder": [
        "What are the phases of an incident response plan?",
        "How do you contain a ransomware attack?",
        "What is digital forensics and how does it relate to incident response?",
        "How do you preserve evidence during an investigation?",
        "What is a chain of custody in cybersecurity?",
        "How do you identify indicators of compromise (IoCs)?",
        "What tools do you use for memory forensics?",
        "How do you communicate with stakeholders during an active incident?",
        "What is a tabletop exercise and how do you run one?",
        "How do you perform a root cause analysis after an incident?",
        "What is the difference between eradication and recovery?",
        "Describe the most challenging incident you have responded to.",
    ],
    "Compliance/GRC Specialist": [
        "What is the difference between a policy, standard, and procedure?",
        "How do you conduct a risk assessment?",
        "What frameworks have you worked with (ISO 27001, NIST, SOC 2)?",
        "How do you prepare for a SOC 2 audit?",
        "What is the difference between a risk register and a risk matrix?",
        "How do you handle third-party risk management?",
        "What is data classification and how do you implement it?",
        "Explain GDPR's right to be forgotten and its technical implications.",
        "How do you track and manage compliance gaps?",
        "What is business continuity planning (BCP)?",
        "How do you communicate compliance requirements to engineering teams?",
        "Describe a compliance program you helped implement.",
    ],
    "IT Project Manager": [
        "What is the difference between Waterfall and Agile project management?",
        "How do you manage project scope creep?",
        "What is a critical path in project scheduling?",
        "How do you manage stakeholder expectations?",
        "What is a RACI matrix and how do you use it?",
        "How do you handle a project that is behind schedule?",
        "What risk management techniques do you use?",
        "How do you run an effective project status meeting?",
        "What is earned value management (EVM)?",
        "How do you manage a distributed/remote project team?",
        "What project management tools have you used (Jira, MS Project, etc.)?",
        "Describe a project that went off track and how you recovered it.",
    ],
    "Product Manager": [
        "How do you prioritize a product backlog?",
        "What is the difference between a product roadmap and a sprint backlog?",
        "How do you define and measure product success metrics?",
        "How do you gather and incorporate customer feedback?",
        "What is the MoSCoW prioritization method?",
        "How do you write a clear user story?",
        "How do you work with engineering teams to estimate effort?",
        "What is product-market fit and how do you measure it?",
        "How do you handle conflicting priorities from different stakeholders?",
        "What is an MVP and how do you decide what goes in it?",
        "How do you use data to make product decisions?",
        "Describe a product you owned and the impact it had on users.",
    ],
    "Business Systems Analyst": [
        "What is the difference between functional and non-functional requirements?",
        "How do you elicit requirements from stakeholders?",
        "What is a use case diagram and how do you create one?",
        "How do you document business processes using BPMN?",
        "What is gap analysis and when do you use it?",
        "How do you validate that a system meets business requirements?",
        "What is the difference between an as-is and to-be process?",
        "How do you manage requirement changes during a project?",
        "What tools do you use for requirements management?",
        "How do you translate business requirements into technical specifications?",
        "What is UAT (User Acceptance Testing) and how do you manage it?",
        "Describe a complex business process you analyzed and improved.",
    ],
    "IT Director / CIO": [
        "How do you align IT strategy with business goals?",
        "How do you build and manage an IT budget?",
        "What is your approach to IT governance?",
        "How do you evaluate and manage technology vendors?",
        "How do you lead digital transformation initiatives?",
        "What is your approach to IT risk management?",
        "How do you build and retain a high-performing IT team?",
        "How do you handle a major technology failure affecting the business?",
        "What frameworks do you use for IT governance (COBIT, ITIL)?",
        "How do you communicate technology strategy to the board?",
        "How do you approach cloud migration at an enterprise level?",
        "Describe a major IT initiative you led and its business outcome.",
    ],
    "Scrum Master": [
        "What is the difference between a Scrum Master and a Project Manager?",
        "How do you facilitate a retrospective effectively?",
        "What do you do when a team member is blocking the sprint?",
        "How do you handle a Product Owner who keeps changing priorities mid-sprint?",
        "What is your approach to removing impediments?",
        "How do you measure team velocity and use it for planning?",
        "What is the difference between Scrum and Kanban?",
        "How do you onboard a new team to Scrum?",
        "What is a Definition of Done and how do you establish one?",
        "How do you handle conflict within a Scrum team?",
        "What Agile scaling frameworks have you worked with (SAFe, LeSS)?",
        "Describe a team you coached to high performance.",
    ],
    "UX/UI Designer": [
        "What is the difference between UX and UI design?",
        "How do you conduct user research?",
        "What is a design system and why is it important?",
        "Explain the concept of information architecture.",
        "What is usability testing and how do you run a session?",
        "How do you approach designing for accessibility (WCAG)?",
        "What is the difference between a wireframe, mockup, and prototype?",
        "How do you use data and analytics to inform design decisions?",
        "What design tools do you use (Figma, Sketch, Adobe XD)?",
        "How do you handle design feedback from engineers and stakeholders?",
        "What is Gestalt theory and how does it apply to UI design?",
        "Walk me through a design project from research to final delivery.",
    ],
    "IT Support Specialist": [
        "How do you troubleshoot a computer that won't boot?",
        "What is Active Directory and how do you manage user accounts?",
        "How do you handle a user who has forgotten their password?",
        "What is DHCP and how does it work?",
        "How do you remotely access and troubleshoot a user's machine?",
        "What is the difference between a virus and a worm?",
        "How do you set up and configure a new employee's workstation?",
        "What is a ticketing system and how do you use it?",
        "How do you prioritize support tickets when multiple critical issues come in?",
        "What is Group Policy and how is it used?",
        "How do you handle an end-user who is frustrated with a technology issue?",
        "Describe the most difficult technical support issue you resolved.",
    ],
    "Technical Writer": [
        "What is the difference between a user guide and an API reference?",
        "How do you structure documentation for a complex software product?",
        "What is docs-as-code and what tools do you use?",
        "How do you gather information from engineers to write documentation?",
        "What is your process for keeping documentation up to date?",
        "How do you write for a non-technical audience?",
        "What style guides have you followed (Google, Microsoft, AP)?",
        "How do you measure the effectiveness of documentation?",
        "What tools do you use for writing and publishing docs (Confluence, MkDocs)?",
        "How do you handle documentation for an API?",
        "What is single-sourcing and why does it matter?",
        "Share an example of documentation you wrote that significantly helped users.",
    ],
    "Database Administrator (DBA)": [
        "What is the difference between a clustered and non-clustered index?",
        "How do you optimize a slow SQL query?",
        "What is database normalization and what are the normal forms?",
        "How do you implement a database backup and recovery strategy?",
        "What is the difference between OLTP and OLAP?",
        "How do you handle database replication?",
        "What is database sharding and when would you use it?",
        "How do you monitor database performance?",
        "What is a stored procedure and when should you use one?",
        "How do you handle schema migrations in a production database?",
        "What is a deadlock and how do you resolve it?",
        "Describe the largest database you have managed and any challenges you faced.",
    ],
}


def get_all_seed_questions():
    """Return list of (role, experience, text) tuples for all seed questions."""
    rows = []
    for role, questions in QUESTIONS_BY_ROLE.items():
        for exp in EXPERIENCE_LEVELS:
            for q in questions:
                rows.append((role, exp, q))
    return rows
